test: 
	g++ -o test_derivative test_derivative_main.cpp
	g++ -o test_gradient_descent test_gradient_descent_main.cpp
	g++ -o test_polynomial_regression test_polynomial_regression_main.cpp
	g++ -o test_logistic_regression test_logistic_regression_main.cpp
	./test_derivative
	./test_gradient_descent
	./test_polynomial_regression
	./test_logistic_regression

clean:
	rm test_derivative
	rm test_gradient_descent
	rm test_polynomial_regression
	rm test_logistic_regression
